version: '3.7'

services:
  database:
    container_name: listvm_db
    build: db
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - listvm_network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - listvm_network
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/

networks: 
  listvm_network:
    driver: bridge
